name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ricardochaves/python-lint@v1.3.0
          with:
            use-pylint: false
            use-pycodestyle: false
            use-mypy: false
            extra-black-options: "--config pyproject.toml --verbose"
            extra-flake8-options: "--verbose"
            extra-isort-options: "--check"
